<?php

namespace AppBundle\Repository;

/**
 * Event_User_LikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Event_User_LikesRepository extends \Doctrine\ORM\EntityRepository
{
}
